# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 615)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 615))
        MainWindow.setMaximumSize(QtCore.QSize(800, 615))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../.designer/backup/icon.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(48, 48))
        MainWindow.setTabShape(QtGui.QTabWidget.Triangular)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.openButton = QtGui.QPushButton(self.centralwidget)
        self.openButton.setEnabled(True)
        self.openButton.setGeometry(QtCore.QRect(10, 10, 81, 20))
        self.openButton.setObjectName(_fromUtf8("openButton"))
        self.dependencyComboBox = QtGui.QComboBox(self.centralwidget)
        self.dependencyComboBox.setEnabled(False)
        self.dependencyComboBox.setGeometry(QtCore.QRect(540, 360, 121, 31))
        self.dependencyComboBox.setObjectName(_fromUtf8("dependencyComboBox"))
        self.deleteDependencyBttn = QtGui.QPushButton(self.centralwidget)
        self.deleteDependencyBttn.setEnabled(False)
        self.deleteDependencyBttn.setGeometry(QtCore.QRect(670, 360, 111, 31))
        self.deleteDependencyBttn.setObjectName(_fromUtf8("deleteDependencyBttn"))
        self.saveButton = QtGui.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(100, 10, 81, 20))
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.changeFeatNameBttn = QtGui.QPushButton(self.centralwidget)
        self.changeFeatNameBttn.setEnabled(False)
        self.changeFeatNameBttn.setGeometry(QtCore.QRect(159, 519, 133, 23))
        self.changeFeatNameBttn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.changeFeatNameBttn.setObjectName(_fromUtf8("changeFeatNameBttn"))
        self.deleteFeatureBttn = QtGui.QPushButton(self.centralwidget)
        self.deleteFeatureBttn.setEnabled(False)
        self.deleteFeatureBttn.setGeometry(QtCore.QRect(159, 489, 93, 23))
        self.deleteFeatureBttn.setObjectName(_fromUtf8("deleteFeatureBttn"))
        self.newModButton = QtGui.QPushButton(self.centralwidget)
        self.newModButton.setGeometry(QtCore.QRect(250, 10, 81, 20))
        self.newModButton.setObjectName(_fromUtf8("newModButton"))
        self.numberOfFeatures = QtGui.QSpinBox(self.centralwidget)
        self.numberOfFeatures.setGeometry(QtCore.QRect(480, 10, 61, 20))
        self.numberOfFeatures.setMinimum(1)
        self.numberOfFeatures.setMaximum(20)
        self.numberOfFeatures.setObjectName(_fromUtf8("numberOfFeatures"))
        self.numberOfFeaturesLayout = QtGui.QLabel(self.centralwidget)
        self.numberOfFeaturesLayout.setGeometry(QtCore.QRect(340, 10, 121, 20))
        self.numberOfFeaturesLayout.setObjectName(_fromUtf8("numberOfFeaturesLayout"))
        self.CATEGORYCOMBOBOX = QtGui.QComboBox(self.centralwidget)
        self.CATEGORYCOMBOBOX.setEnabled(True)
        self.CATEGORYCOMBOBOX.setGeometry(QtCore.QRect(480, 60, 121, 22))
        self.CATEGORYCOMBOBOX.setObjectName(_fromUtf8("CATEGORYCOMBOBOX"))
        self.removeCategoryButton = QtGui.QPushButton(self.centralwidget)
        self.removeCategoryButton.setEnabled(False)
        self.removeCategoryButton.setGeometry(QtCore.QRect(610, 99, 111, 23))
        self.removeCategoryButton.setObjectName(_fromUtf8("removeCategoryButton"))
        self.editCategoryButton = QtGui.QPushButton(self.centralwidget)
        self.editCategoryButton.setEnabled(False)
        self.editCategoryButton.setGeometry(QtCore.QRect(610, 59, 111, 23))
        self.editCategoryButton.setObjectName(_fromUtf8("editCategoryButton"))
        self.confirmButton = QtGui.QPushButton(self.centralwidget)
        self.confirmButton.setEnabled(False)
        self.confirmButton.setGeometry(QtCore.QRect(10, 210, 201, 23))
        self.confirmButton.setObjectName(_fromUtf8("confirmButton"))
        self.saveCategoryChanges = QtGui.QPushButton(self.centralwidget)
        self.saveCategoryChanges.setEnabled(False)
        self.saveCategoryChanges.setGeometry(QtCore.QRect(250, 210, 131, 23))
        self.saveCategoryChanges.setObjectName(_fromUtf8("saveCategoryChanges"))
        self.FeatureTabs = QtGui.QTabWidget(self.centralwidget)
        self.FeatureTabs.setGeometry(QtCore.QRect(10, 250, 221, 161))
        self.FeatureTabs.setObjectName(_fromUtf8("FeatureTabs"))
        self.FeatureTab = QtGui.QWidget()
        self.FeatureTab.setObjectName(_fromUtf8("FeatureTab"))
        self.label_10 = QtGui.QLabel(self.FeatureTab)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 109, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.descEdit = QtGui.QLineEdit(self.FeatureTab)
        self.descEdit.setEnabled(True)
        self.descEdit.setGeometry(QtCore.QRect(100, 10, 101, 21))
        self.descEdit.setText(_fromUtf8(""))
        self.descEdit.setObjectName(_fromUtf8("descEdit"))
        self.label_12 = QtGui.QLabel(self.FeatureTab)
        self.label_12.setGeometry(QtCore.QRect(10, 40, 109, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.unlockEdit = QtGui.QLineEdit(self.FeatureTab)
        self.unlockEdit.setEnabled(True)
        self.unlockEdit.setGeometry(QtCore.QRect(100, 40, 101, 21))
        self.unlockEdit.setObjectName(_fromUtf8("unlockEdit"))
        self.devtimeEdit = QtGui.QLineEdit(self.FeatureTab)
        self.devtimeEdit.setEnabled(True)
        self.devtimeEdit.setGeometry(QtCore.QRect(100, 70, 101, 21))
        self.devtimeEdit.setObjectName(_fromUtf8("devtimeEdit"))
        self.label_13 = QtGui.QLabel(self.FeatureTab)
        self.label_13.setGeometry(QtCore.QRect(10, 70, 109, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.FeatureTab)
        self.label_14.setGeometry(QtCore.QRect(10, 100, 109, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.innovationEdit = QtGui.QLineEdit(self.FeatureTab)
        self.innovationEdit.setEnabled(True)
        self.innovationEdit.setGeometry(QtCore.QRect(100, 100, 101, 21))
        self.innovationEdit.setObjectName(_fromUtf8("innovationEdit"))
        self.FeatureTabs.addTab(self.FeatureTab, _fromUtf8(""))
        self.FeatureTab2 = QtGui.QWidget()
        self.FeatureTab2.setObjectName(_fromUtf8("FeatureTab2"))
        self.label_11 = QtGui.QLabel(self.FeatureTab2)
        self.label_11.setGeometry(QtCore.QRect(0, 10, 109, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.usabilityEdit = QtGui.QLineEdit(self.FeatureTab2)
        self.usabilityEdit.setEnabled(True)
        self.usabilityEdit.setGeometry(QtCore.QRect(100, 10, 101, 21))
        self.usabilityEdit.setObjectName(_fromUtf8("usabilityEdit"))
        self.stabilityEdit = QtGui.QLineEdit(self.FeatureTab2)
        self.stabilityEdit.setEnabled(True)
        self.stabilityEdit.setGeometry(QtCore.QRect(100, 40, 101, 21))
        self.stabilityEdit.setObjectName(_fromUtf8("stabilityEdit"))
        self.codeartEdit = QtGui.QLineEdit(self.FeatureTab2)
        self.codeartEdit.setEnabled(True)
        self.codeartEdit.setGeometry(QtCore.QRect(100, 70, 101, 21))
        self.codeartEdit.setObjectName(_fromUtf8("codeartEdit"))
        self.serverEdit = QtGui.QLineEdit(self.FeatureTab2)
        self.serverEdit.setEnabled(True)
        self.serverEdit.setGeometry(QtCore.QRect(100, 100, 101, 21))
        self.serverEdit.setObjectName(_fromUtf8("serverEdit"))
        self.label_15 = QtGui.QLabel(self.FeatureTab2)
        self.label_15.setGeometry(QtCore.QRect(0, 40, 109, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_17 = QtGui.QLabel(self.FeatureTab2)
        self.label_17.setGeometry(QtCore.QRect(0, 70, 109, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.ServerLabel = QtGui.QLabel(self.FeatureTab2)
        self.ServerLabel.setGeometry(QtCore.QRect(0, 100, 109, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.ServerLabel.setFont(font)
        self.ServerLabel.setObjectName(_fromUtf8("ServerLabel"))
        self.FeatureTabs.addTab(self.FeatureTab2, _fromUtf8(""))
        self.FeatureTab3 = QtGui.QWidget()
        self.FeatureTab3.setObjectName(_fromUtf8("FeatureTab3"))
        self.FORCEDCHECKBOX = QtGui.QCheckBox(self.FeatureTab3)
        self.FORCEDCHECKBOX.setEnabled(True)
        self.FORCEDCHECKBOX.setGeometry(QtCore.QRect(10, 3, 101, 43))
        self.FORCEDCHECKBOX.setObjectName(_fromUtf8("FORCEDCHECKBOX"))
        self.FROMCHECKBOX = QtGui.QCheckBox(self.FeatureTab3)
        self.FROMCHECKBOX.setGeometry(QtCore.QRect(130, 40, 71, 30))
        self.FROMCHECKBOX.setObjectName(_fromUtf8("FROMCHECKBOX"))
        self.fromLE = QtGui.QLineEdit(self.FeatureTab3)
        self.fromLE.setGeometry(QtCore.QRect(10, 40, 101, 21))
        self.fromLE.setObjectName(_fromUtf8("fromLE"))
        self.VITALCHECKBOX = QtGui.QCheckBox(self.FeatureTab3)
        self.VITALCHECKBOX.setGeometry(QtCore.QRect(130, 3, 61, 43))
        self.VITALCHECKBOX.setObjectName(_fromUtf8("VITALCHECKBOX"))
        self.savechanges = QtGui.QPushButton(self.FeatureTab3)
        self.savechanges.setGeometry(QtCore.QRect(10, 89, 101, 31))
        self.savechanges.setObjectName(_fromUtf8("savechanges"))
        self.FeatureTabs.addTab(self.FeatureTab3, _fromUtf8(""))
        self.tabWidget_2 = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 40, 201, 161))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.label_2 = QtGui.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 89, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_8 = QtGui.QLabel(self.tab_4)
        self.label_8.setGeometry(QtCore.QRect(10, 30, 89, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label = QtGui.QLabel(self.tab_4)
        self.label.setGeometry(QtCore.QRect(10, 60, 89, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_4 = QtGui.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 89, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.nameEdit = QtGui.QLineEdit(self.tab_4)
        self.nameEdit.setEnabled(True)
        self.nameEdit.setGeometry(QtCore.QRect(85, 10, 99, 20))
        self.nameEdit.setObjectName(_fromUtf8("nameEdit"))
        self.categoryEdit = QtGui.QLineEdit(self.tab_4)
        self.categoryEdit.setGeometry(QtCore.QRect(85, 40, 99, 20))
        self.categoryEdit.setObjectName(_fromUtf8("categoryEdit"))
        self.descriptionEdit = QtGui.QLineEdit(self.tab_4)
        self.descriptionEdit.setGeometry(QtCore.QRect(85, 70, 99, 20))
        self.descriptionEdit.setObjectName(_fromUtf8("descriptionEdit"))
        self.randomEdit = QtGui.QLineEdit(self.tab_4)
        self.randomEdit.setGeometry(QtCore.QRect(85, 100, 99, 20))
        self.randomEdit.setObjectName(_fromUtf8("randomEdit"))
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.label_7 = QtGui.QLabel(self.tab_5)
        self.label_7.setGeometry(QtCore.QRect(10, 0, 89, 39))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_6 = QtGui.QLabel(self.tab_5)
        self.label_6.setGeometry(QtCore.QRect(10, 30, 89, 39))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_5 = QtGui.QLabel(self.tab_5)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 89, 39))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_3 = QtGui.QLabel(self.tab_5)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 89, 39))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.fUnlockEdit = QtGui.QLineEdit(self.tab_5)
        self.fUnlockEdit.setGeometry(QtCore.QRect(85, 10, 99, 21))
        self.fUnlockEdit.setObjectName(_fromUtf8("fUnlockEdit"))
        self.populationEdit = QtGui.QLineEdit(self.tab_5)
        self.populationEdit.setGeometry(QtCore.QRect(85, 40, 99, 21))
        self.populationEdit.setObjectName(_fromUtf8("populationEdit"))
        self.ossEdit = QtGui.QLineEdit(self.tab_5)
        self.ossEdit.setGeometry(QtCore.QRect(85, 70, 99, 21))
        self.ossEdit.setObjectName(_fromUtf8("ossEdit"))
        self.houseEdit = QtGui.QLineEdit(self.tab_5)
        self.houseEdit.setGeometry(QtCore.QRect(85, 100, 99, 21))
        self.houseEdit.setObjectName(_fromUtf8("houseEdit"))
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.label_24 = QtGui.QLabel(self.tab_6)
        self.label_24.setGeometry(QtCore.QRect(10, 0, 89, 39))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.tab_6)
        self.label_25.setGeometry(QtCore.QRect(10, 30, 89, 39))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_23 = QtGui.QLabel(self.tab_6)
        self.label_23.setGeometry(QtCore.QRect(10, 60, 109, 39))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.retentionEdit = QtGui.QLineEdit(self.tab_6)
        self.retentionEdit.setGeometry(QtCore.QRect(80, 10, 99, 21))
        self.retentionEdit.setObjectName(_fromUtf8("retentionEdit"))
        self.iterativeEdit = QtGui.QLineEdit(self.tab_6)
        self.iterativeEdit.setGeometry(QtCore.QRect(80, 40, 99, 21))
        self.iterativeEdit.setObjectName(_fromUtf8("iterativeEdit"))
        self.nameGeneratorEdit = QtGui.QLineEdit(self.tab_6)
        self.nameGeneratorEdit.setGeometry(QtCore.QRect(10, 90, 171, 21))
        self.nameGeneratorEdit.setObjectName(_fromUtf8("nameGeneratorEdit"))
        self.tabWidget_2.addTab(self.tab_6, _fromUtf8(""))
        self.tabWidget_3 = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_3.setGeometry(QtCore.QRect(250, 40, 211, 171))
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.CATEGORIESCHECKBOX = QtGui.QCheckBox(self.tab_7)
        self.CATEGORIESCHECKBOX.setEnabled(False)
        self.CATEGORIESCHECKBOX.setGeometry(QtCore.QRect(10, 10, 101, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.CATEGORIESCHECKBOX.setFont(font)
        self.CATEGORIESCHECKBOX.setObjectName(_fromUtf8("CATEGORIESCHECKBOX"))
        self.categoryNameEdit = QtGui.QLineEdit(self.tab_7)
        self.categoryNameEdit.setEnabled(False)
        self.categoryNameEdit.setGeometry(QtCore.QRect(10, 30, 121, 20))
        self.categoryNameEdit.setObjectName(_fromUtf8("categoryNameEdit"))
        self.label_28 = QtGui.QLabel(self.tab_7)
        self.label_28.setGeometry(QtCore.QRect(10, 70, 71, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.cDescriptionEdit = QtGui.QLineEdit(self.tab_7)
        self.cDescriptionEdit.setEnabled(False)
        self.cDescriptionEdit.setGeometry(QtCore.QRect(10, 90, 171, 20))
        self.cDescriptionEdit.setObjectName(_fromUtf8("cDescriptionEdit"))
        self.tabWidget_3.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.label_29 = QtGui.QLabel(self.tab_8)
        self.label_29.setGeometry(QtCore.QRect(0, 10, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.cUnlockEdit = QtGui.QLineEdit(self.tab_8)
        self.cUnlockEdit.setEnabled(False)
        self.cUnlockEdit.setGeometry(QtCore.QRect(80, 10, 101, 20))
        self.cUnlockEdit.setObjectName(_fromUtf8("cUnlockEdit"))
        self.label_30 = QtGui.QLabel(self.tab_8)
        self.label_30.setGeometry(QtCore.QRect(0, 40, 71, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.cPopularityEdit = QtGui.QLineEdit(self.tab_8)
        self.cPopularityEdit.setEnabled(False)
        self.cPopularityEdit.setGeometry(QtCore.QRect(80, 40, 101, 20))
        self.cPopularityEdit.setObjectName(_fromUtf8("cPopularityEdit"))
        self.cTimeScaleEdit = QtGui.QLineEdit(self.tab_8)
        self.cTimeScaleEdit.setEnabled(False)
        self.cTimeScaleEdit.setGeometry(QtCore.QRect(80, 70, 101, 20))
        self.cTimeScaleEdit.setObjectName(_fromUtf8("cTimeScaleEdit"))
        self.label_31 = QtGui.QLabel(self.tab_8)
        self.label_31.setGeometry(QtCore.QRect(0, 70, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.cRetentionEdit = QtGui.QLineEdit(self.tab_8)
        self.cRetentionEdit.setGeometry(QtCore.QRect(80, 100, 101, 21))
        self.cRetentionEdit.setObjectName(_fromUtf8("cRetentionEdit"))
        self.label_32 = QtGui.QLabel(self.tab_8)
        self.label_32.setGeometry(QtCore.QRect(0, 100, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.tabWidget_3.addTab(self.tab_8, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.label_33 = QtGui.QLabel(self.tab_9)
        self.label_33.setGeometry(QtCore.QRect(10, 40, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.cIterativeEdit = QtGui.QLineEdit(self.tab_9)
        self.cIterativeEdit.setGeometry(QtCore.QRect(70, 40, 101, 21))
        self.cIterativeEdit.setObjectName(_fromUtf8("cIterativeEdit"))
        self.label_34 = QtGui.QLabel(self.tab_9)
        self.label_34.setGeometry(QtCore.QRect(10, 70, 121, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.cNameGeneratorEdit = QtGui.QLineEdit(self.tab_9)
        self.cNameGeneratorEdit.setGeometry(QtCore.QRect(10, 90, 161, 21))
        self.cNameGeneratorEdit.setObjectName(_fromUtf8("cNameGeneratorEdit"))
        self.addCategoryButton = QtGui.QPushButton(self.tab_9)
        self.addCategoryButton.setEnabled(False)
        self.addCategoryButton.setGeometry(QtCore.QRect(10, 120, 161, 23))
        self.addCategoryButton.setObjectName(_fromUtf8("addCategoryButton"))
        self.tabWidget_3.addTab(self.tab_9, _fromUtf8(""))
        self.tabWidget_4 = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_4.setGeometry(QtCore.QRect(250, 250, 531, 101))
        self.tabWidget_4.setObjectName(_fromUtf8("tabWidget_4"))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.OSDEPBOX = QtGui.QComboBox(self.tab_10)
        self.OSDEPBOX.setEnabled(True)
        self.OSDEPBOX.setGeometry(QtCore.QRect(10, 10, 230, 22))
        self.OSDEPBOX.setObjectName(_fromUtf8("OSDEPBOX"))
        self.OSDEPBOX.addItem(_fromUtf8(""))
        self.OSDEPBOX.addItem(_fromUtf8(""))
        self.OSDEPBOX.addItem(_fromUtf8(""))
        self.OSDEPBOX.addItem(_fromUtf8(""))
        self.OSDEPBOX.addItem(_fromUtf8(""))
        self.OSDEPBOX.addItem(_fromUtf8(""))
        self.OSDEPBOX.addItem(_fromUtf8(""))
        self.OSDEPBOX.addItem(_fromUtf8(""))
        self.OSDEPBOX.addItem(_fromUtf8(""))
        self.OSDEPBOX.addItem(_fromUtf8(""))
        self.OSDEPBOX.addItem(_fromUtf8(""))
        self.OSDEPBOX.addItem(_fromUtf8(""))
        self.OSDEPBOX.addItem(_fromUtf8(""))
        self.OSCHECKBOX = QtGui.QCheckBox(self.tab_10)
        self.OSCHECKBOX.setGeometry(QtCore.QRect(250, 10, 139, 17))
        self.OSCHECKBOX.setObjectName(_fromUtf8("OSCHECKBOX"))
        self.addOSDependencyBttn = QtGui.QPushButton(self.tab_10)
        self.addOSDependencyBttn.setEnabled(False)
        self.addOSDependencyBttn.setGeometry(QtCore.QRect(250, 30, 120, 21))
        self.addOSDependencyBttn.setObjectName(_fromUtf8("addOSDependencyBttn"))
        self.tabWidget_4.addTab(self.tab_10, _fromUtf8(""))
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName(_fromUtf8("tab_11"))
        self.VISUALDEPBOX = QtGui.QComboBox(self.tab_11)
        self.VISUALDEPBOX.setEnabled(True)
        self.VISUALDEPBOX.setGeometry(QtCore.QRect(10, 10, 230, 22))
        self.VISUALDEPBOX.setObjectName(_fromUtf8("VISUALDEPBOX"))
        self.VISUALDEPBOX.addItem(_fromUtf8(""))
        self.VISUALDEPBOX.addItem(_fromUtf8(""))
        self.VISUALDEPBOX.addItem(_fromUtf8(""))
        self.VISCHECKBOX = QtGui.QCheckBox(self.tab_11)
        self.VISCHECKBOX.setGeometry(QtCore.QRect(260, 10, 139, 17))
        self.VISCHECKBOX.setObjectName(_fromUtf8("VISCHECKBOX"))
        self.addVisualDependencyBttn = QtGui.QPushButton(self.tab_11)
        self.addVisualDependencyBttn.setEnabled(False)
        self.addVisualDependencyBttn.setGeometry(QtCore.QRect(260, 40, 120, 20))
        self.addVisualDependencyBttn.setObjectName(_fromUtf8("addVisualDependencyBttn"))
        self.tabWidget_4.addTab(self.tab_11, _fromUtf8(""))
        self.tab_12 = QtGui.QWidget()
        self.tab_12.setObjectName(_fromUtf8("tab_12"))
        self.AUDIODEPBOX = QtGui.QComboBox(self.tab_12)
        self.AUDIODEPBOX.setEnabled(True)
        self.AUDIODEPBOX.setGeometry(QtCore.QRect(10, 10, 230, 22))
        self.AUDIODEPBOX.setObjectName(_fromUtf8("AUDIODEPBOX"))
        self.AUDIODEPBOX.addItem(_fromUtf8(""))
        self.AUDIODEPBOX.addItem(_fromUtf8(""))
        self.AUDIODEPBOX.addItem(_fromUtf8(""))
        self.AUDCHECKBOX = QtGui.QCheckBox(self.tab_12)
        self.AUDCHECKBOX.setGeometry(QtCore.QRect(260, 10, 139, 17))
        self.AUDCHECKBOX.setObjectName(_fromUtf8("AUDCHECKBOX"))
        self.addAudioDependencyBttn = QtGui.QPushButton(self.tab_12)
        self.addAudioDependencyBttn.setEnabled(False)
        self.addAudioDependencyBttn.setGeometry(QtCore.QRect(260, 40, 120, 20))
        self.addAudioDependencyBttn.setObjectName(_fromUtf8("addAudioDependencyBttn"))
        self.tabWidget_4.addTab(self.tab_12, _fromUtf8(""))
        self.tab_13 = QtGui.QWidget()
        self.tab_13.setObjectName(_fromUtf8("tab_13"))
        self.label_19 = QtGui.QLabel(self.tab_13)
        self.label_19.setGeometry(QtCore.QRect(10, 10, 171, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.featureDepLE = QtGui.QLineEdit(self.tab_13)
        self.featureDepLE.setGeometry(QtCore.QRect(280, 40, 150, 21))
        self.featureDepLE.setObjectName(_fromUtf8("featureDepLE"))
        self.softwareDepLE = QtGui.QLineEdit(self.tab_13)
        self.softwareDepLE.setGeometry(QtCore.QRect(80, 40, 121, 21))
        self.softwareDepLE.setObjectName(_fromUtf8("softwareDepLE"))
        self.label_22 = QtGui.QLabel(self.tab_13)
        self.label_22.setGeometry(QtCore.QRect(210, 43, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_20 = QtGui.QLabel(self.tab_13)
        self.label_20.setGeometry(QtCore.QRect(10, 43, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.addCustomDependencyButton = QtGui.QPushButton(self.tab_13)
        self.addCustomDependencyButton.setEnabled(False)
        self.addCustomDependencyButton.setGeometry(QtCore.QRect(280, 10, 151, 21))
        self.addCustomDependencyButton.setObjectName(_fromUtf8("addCustomDependencyButton"))
        self.tabWidget_4.addTab(self.tab_13, _fromUtf8(""))
        self.dependBox = QtGui.QComboBox(self.centralwidget)
        self.dependBox.setGeometry(QtCore.QRect(250, 360, 121, 31))
        self.dependBox.setObjectName(_fromUtf8("dependBox"))
        self.deleteCustomDepButton = QtGui.QPushButton(self.centralwidget)
        self.deleteCustomDepButton.setGeometry(QtCore.QRect(380, 360, 151, 31))
        self.deleteCustomDepButton.setObjectName(_fromUtf8("deleteCustomDepButton"))
        self.newNameEdit = QtGui.QLineEdit(self.centralwidget)
        self.newNameEdit.setGeometry(QtCore.QRect(20, 520, 121, 23))
        self.newNameEdit.setObjectName(_fromUtf8("newNameEdit"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 240, 790, 3))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(230, 0, 3, 240))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(240, 240, 3, 170))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(240, 410, 550, 3))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(790, 240, 3, 170))
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.featureComboBox = QtGui.QComboBox(self.centralwidget)
        self.featureComboBox.setEnabled(True)
        self.featureComboBox.setGeometry(QtCore.QRect(20, 459, 121, 23))
        self.featureComboBox.setEditable(False)
        self.featureComboBox.setObjectName(_fromUtf8("featureComboBox"))
        self.editFeatureBttn = QtGui.QPushButton(self.centralwidget)
        self.editFeatureBttn.setEnabled(False)
        self.editFeatureBttn.setGeometry(QtCore.QRect(159, 459, 93, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editFeatureBttn.sizePolicy().hasHeightForWidth())
        self.editFeatureBttn.setSizePolicy(sizePolicy)
        self.editFeatureBttn.setMaximumSize(QtCore.QSize(200, 25))
        self.editFeatureBttn.setObjectName(_fromUtf8("editFeatureBttn"))
        self.funcName = QtGui.QLineEdit(self.centralwidget)
        self.funcName.setEnabled(False)
        self.funcName.setGeometry(QtCore.QRect(20, 429, 121, 23))
        self.funcName.setMaximumSize(QtCore.QSize(121, 16777215))
        self.funcName.setObjectName(_fromUtf8("funcName"))
        self.addFeatureBttn = QtGui.QPushButton(self.centralwidget)
        self.addFeatureBttn.setEnabled(False)
        self.addFeatureBttn.setGeometry(QtCore.QRect(159, 429, 93, 23))
        self.addFeatureBttn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.addFeatureBttn.setObjectName(_fromUtf8("addFeatureBttn"))
        self.line_7 = QtGui.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(300, 420, 3, 140))
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.line_8 = QtGui.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(10, 420, 3, 140))
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.line_9 = QtGui.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(10, 420, 290, 3))
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.line_10 = QtGui.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(10, 560, 290, 3))
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.FeatureTabs.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(2)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Modding Tool", None))
        self.openButton.setText(_translate("MainWindow", "Open File", None))
        self.deleteDependencyBttn.setText(_translate("MainWindow", "Delete Dependency", None))
        self.saveButton.setText(_translate("MainWindow", "Save", None))
        self.changeFeatNameBttn.setText(_translate("MainWindow", "Change Feature Name", None))
        self.deleteFeatureBttn.setText(_translate("MainWindow", "Delete Feature", None))
        self.newModButton.setText(_translate("MainWindow", "New Mod", None))
        self.numberOfFeaturesLayout.setText(_translate("MainWindow", "Number Of Features", None))
        self.removeCategoryButton.setText(_translate("MainWindow", "Remove Category", None))
        self.editCategoryButton.setText(_translate("MainWindow", "Edit Category", None))
        self.confirmButton.setText(_translate("MainWindow", "Save Changes to Software Type", None))
        self.saveCategoryChanges.setText(_translate("MainWindow", "Save Category Changes", None))
        self.label_10.setText(_translate("MainWindow", "Description", None))
        self.label_12.setText(_translate("MainWindow", "Unlock", None))
        self.label_13.setText(_translate("MainWindow", "DevTime", None))
        self.label_14.setText(_translate("MainWindow", "Innovation", None))
        self.FeatureTabs.setTabText(self.FeatureTabs.indexOf(self.FeatureTab), _translate("MainWindow", "Page 1", None))
        self.label_11.setText(_translate("MainWindow", "Usability", None))
        self.label_15.setText(_translate("MainWindow", "Stability", None))
        self.label_17.setText(_translate("MainWindow", "CodeArt", None))
        self.ServerLabel.setText(_translate("MainWindow", "Server", None))
        self.FeatureTabs.setTabText(self.FeatureTabs.indexOf(self.FeatureTab2), _translate("MainWindow", "Page 2", None))
        self.FORCEDCHECKBOX.setText(_translate("MainWindow", "Forced Feature", None))
        self.FROMCHECKBOX.setText(_translate("MainWindow", "From Tag", None))
        self.VITALCHECKBOX.setText(_translate("MainWindow", "Vital", None))
        self.savechanges.setText(_translate("MainWindow", "Save Changes", None))
        self.FeatureTabs.setTabText(self.FeatureTabs.indexOf(self.FeatureTab3), _translate("MainWindow", "Page 3", None))
        self.label_2.setText(_translate("MainWindow", "Name       ", None))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Category</span></p></body></html>", None))
        self.label.setText(_translate("MainWindow", "Description", None))
        self.label_4.setText(_translate("MainWindow", "Random    ", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Page 1", None))
        self.label_7.setText(_translate("MainWindow", "Unlock     ", None))
        self.label_6.setText(_translate("MainWindow", "Population ", None))
        self.label_5.setText(_translate("MainWindow", "OSSpecific", None))
        self.label_3.setText(_translate("MainWindow", "InHouse", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Page 2", None))
        self.label_24.setText(_translate("MainWindow", "Retention", None))
        self.label_25.setText(_translate("MainWindow", "Iterative", None))
        self.label_23.setText(_translate("MainWindow", "Name Generator", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Page 3", None))
        self.CATEGORIESCHECKBOX.setText(_translate("MainWindow", "Categories", None))
        self.label_28.setText(_translate("MainWindow", "Description", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "Page 1", None))
        self.label_29.setText(_translate("MainWindow", "Unlock", None))
        self.label_30.setText(_translate("MainWindow", "Popularity", None))
        self.label_31.setText(_translate("MainWindow", "TimeScale", None))
        self.label_32.setText(_translate("MainWindow", "Retention", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Page 2", None))
        self.label_33.setText(_translate("MainWindow", "Iterative", None))
        self.label_34.setText(_translate("MainWindow", "Name Generator", None))
        self.addCategoryButton.setText(_translate("MainWindow", "Add Category", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("MainWindow", "Page 3", None))
        self.OSDEPBOX.setItemText(0, _translate("MainWindow", "Terminal", None))
        self.OSDEPBOX.setItemText(1, _translate("MainWindow", "GUI", None))
        self.OSDEPBOX.setItemText(2, _translate("MainWindow", "3D rendering", None))
        self.OSDEPBOX.setItemText(3, _translate("MainWindow", "Keyboard input", None))
        self.OSDEPBOX.setItemText(4, _translate("MainWindow", "Plug \'n\' Play", None))
        self.OSDEPBOX.setItemText(5, _translate("MainWindow", "Multitasking", None))
        self.OSDEPBOX.setItemText(6, _translate("MainWindow", "Multithreading", None))
        self.OSDEPBOX.setItemText(7, _translate("MainWindow", "Networking", None))
        self.OSDEPBOX.setItemText(8, _translate("MainWindow", "Auto-update", None))
        self.OSDEPBOX.setItemText(9, _translate("MainWindow", "PC speaker", None))
        self.OSDEPBOX.setItemText(10, _translate("MainWindow", "8-bit audio", None))
        self.OSDEPBOX.setItemText(11, _translate("MainWindow", "HD audio", None))
        self.OSDEPBOX.setItemText(12, _translate("MainWindow", "64-bit", None))
        self.OSCHECKBOX.setText(_translate("MainWindow", "OS Dependencies", None))
        self.addOSDependencyBttn.setText(_translate("MainWindow", "Add Dependency", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_10), _translate("MainWindow", "OS Dependencies", None))
        self.VISUALDEPBOX.setItemText(0, _translate("MainWindow", "Image viewing", None))
        self.VISUALDEPBOX.setItemText(1, _translate("MainWindow", "Image editing", None))
        self.VISUALDEPBOX.setItemText(2, _translate("MainWindow", "3D editor", None))
        self.VISCHECKBOX.setText(_translate("MainWindow", "Visual Dependencies", None))
        self.addVisualDependencyBttn.setText(_translate("MainWindow", "Add Dependency", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_11), _translate("MainWindow", "Visual Dependencies", None))
        self.AUDIODEPBOX.setItemText(0, _translate("MainWindow", "Audio playback", None))
        self.AUDIODEPBOX.setItemText(1, _translate("MainWindow", "Recording", None))
        self.AUDIODEPBOX.setItemText(2, _translate("MainWindow", "Music editor", None))
        self.AUDCHECKBOX.setText(_translate("MainWindow", "Audio Dependencies", None))
        self.addAudioDependencyBttn.setText(_translate("MainWindow", "Add Dependency", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_12), _translate("MainWindow", "Audio Dependencies", None))
        self.label_19.setText(_translate("MainWindow", "Custom Dependencies:", None))
        self.label_22.setText(_translate("MainWindow", "Feature", None))
        self.label_20.setText(_translate("MainWindow", "Software", None))
        self.addCustomDependencyButton.setText(_translate("MainWindow", "Add Custom Dependency", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_13), _translate("MainWindow", "Custom Dependencies", None))
        self.deleteCustomDepButton.setText(_translate("MainWindow", "Delete Custom Dependency", None))
        self.editFeatureBttn.setText(_translate("MainWindow", "Edit Feature", None))
        self.funcName.setText(_translate("MainWindow", "Feature", None))
        self.funcName.setPlaceholderText(_translate("MainWindow", "Function", None))
        self.addFeatureBttn.setText(_translate("MainWindow", "Add Feature", None))

