# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(760, 540)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(760, 540))
        MainWindow.setMaximumSize(QtCore.QSize(760, 540))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../.designer/backup/icon.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(48, 48))
        MainWindow.setTabShape(QtGui.QTabWidget.Triangular)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.openButton = QtGui.QPushButton(self.centralwidget)
        self.openButton.setEnabled(True)
        self.openButton.setGeometry(QtCore.QRect(10, 10, 81, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(9)
        self.openButton.setFont(font)
        self.openButton.setObjectName(_fromUtf8("openButton"))
        self.saveButton = QtGui.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(100, 10, 81, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(9)
        self.saveButton.setFont(font)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.newModButton = QtGui.QPushButton(self.centralwidget)
        self.newModButton.setGeometry(QtCore.QRect(250, 10, 81, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(9)
        self.newModButton.setFont(font)
        self.newModButton.setObjectName(_fromUtf8("newModButton"))
        self.featureNum = QtGui.QSpinBox(self.centralwidget)
        self.featureNum.setGeometry(QtCore.QRect(480, 10, 61, 20))
        self.featureNum.setMinimum(1)
        self.featureNum.setMaximum(20)
        self.featureNum.setObjectName(_fromUtf8("featureNum"))
        self.numberOfFeaturesLayout = QtGui.QLabel(self.centralwidget)
        self.numberOfFeaturesLayout.setGeometry(QtCore.QRect(340, 10, 121, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(9)
        self.numberOfFeaturesLayout.setFont(font)
        self.numberOfFeaturesLayout.setObjectName(_fromUtf8("numberOfFeaturesLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 40, 741, 461))
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.softwareTab = QtGui.QWidget()
        self.softwareTab.setObjectName(_fromUtf8("softwareTab"))
        self.saveSoftwareButton = QtGui.QPushButton(self.softwareTab)
        self.saveSoftwareButton.setEnabled(True)
        self.saveSoftwareButton.setGeometry(QtCore.QRect(20, 390, 171, 23))
        self.saveSoftwareButton.setObjectName(_fromUtf8("saveSoftwareButton"))
        self.cComboBox = QtGui.QComboBox(self.softwareTab)
        self.cComboBox.setEnabled(False)
        self.cComboBox.setGeometry(QtCore.QRect(320, 60, 121, 22))
        self.cComboBox.setObjectName(_fromUtf8("cComboBox"))
        self.saveCategoryChanges = QtGui.QPushButton(self.softwareTab)
        self.saveCategoryChanges.setEnabled(True)
        self.saveCategoryChanges.setGeometry(QtCore.QRect(320, 390, 131, 23))
        self.saveCategoryChanges.setObjectName(_fromUtf8("saveCategoryChanges"))
        self.removeCategoryButton = QtGui.QPushButton(self.softwareTab)
        self.removeCategoryButton.setEnabled(False)
        self.removeCategoryButton.setGeometry(QtCore.QRect(449, 59, 103, 23))
        self.removeCategoryButton.setObjectName(_fromUtf8("removeCategoryButton"))
        self.categoryField = QtGui.QLineEdit(self.softwareTab)
        self.categoryField.setGeometry(QtCore.QRect(95, 60, 191, 20))
        self.categoryField.setObjectName(_fromUtf8("categoryField"))
        self.label_2 = QtGui.QLabel(self.softwareTab)
        self.label_2.setGeometry(QtCore.QRect(15, 25, 89, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label = QtGui.QLabel(self.softwareTab)
        self.label.setGeometry(QtCore.QRect(15, 85, 89, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_8 = QtGui.QLabel(self.softwareTab)
        self.label_8.setGeometry(QtCore.QRect(15, 55, 89, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.description = QtGui.QLineEdit(self.softwareTab)
        self.description.setGeometry(QtCore.QRect(95, 90, 191, 20))
        self.description.setObjectName(_fromUtf8("description"))
        self.label_4 = QtGui.QLabel(self.softwareTab)
        self.label_4.setGeometry(QtCore.QRect(20, 200, 89, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.nameField = QtGui.QLineEdit(self.softwareTab)
        self.nameField.setEnabled(True)
        self.nameField.setGeometry(QtCore.QRect(95, 30, 191, 20))
        self.nameField.setObjectName(_fromUtf8("nameField"))
        self.label_3 = QtGui.QLabel(self.softwareTab)
        self.label_3.setGeometry(QtCore.QRect(15, 170, 89, 39))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_5 = QtGui.QLabel(self.softwareTab)
        self.label_5.setGeometry(QtCore.QRect(15, 140, 89, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.inHouse = QtGui.QLineEdit(self.softwareTab)
        self.inHouse.setGeometry(QtCore.QRect(95, 180, 121, 21))
        self.inHouse.setObjectName(_fromUtf8("inHouse"))
        self.unlock = QtGui.QLineEdit(self.softwareTab)
        self.unlock.setGeometry(QtCore.QRect(95, 120, 121, 21))
        self.unlock.setObjectName(_fromUtf8("unlock"))
        self.osSpecific = QtGui.QLineEdit(self.softwareTab)
        self.osSpecific.setGeometry(QtCore.QRect(95, 150, 121, 21))
        self.osSpecific.setObjectName(_fromUtf8("osSpecific"))
        self.label_7 = QtGui.QLabel(self.softwareTab)
        self.label_7.setGeometry(QtCore.QRect(15, 110, 89, 39))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.nameGenerator = QtGui.QLineEdit(self.softwareTab)
        self.nameGenerator.setGeometry(QtCore.QRect(20, 350, 171, 21))
        self.nameGenerator.setObjectName(_fromUtf8("nameGenerator"))
        self.label_23 = QtGui.QLabel(self.softwareTab)
        self.label_23.setGeometry(QtCore.QRect(20, 320, 109, 39))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.categoryCheckbox = QtGui.QCheckBox(self.softwareTab)
        self.categoryCheckbox.setEnabled(True)
        self.categoryCheckbox.setGeometry(QtCore.QRect(320, 30, 101, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.categoryCheckbox.setFont(font)
        self.categoryCheckbox.setObjectName(_fromUtf8("categoryCheckbox"))
        self.categName = QtGui.QLineEdit(self.softwareTab)
        self.categName.setEnabled(True)
        self.categName.setGeometry(QtCore.QRect(400, 110, 151, 20))
        self.categName.setObjectName(_fromUtf8("categName"))
        self.label_28 = QtGui.QLabel(self.softwareTab)
        self.label_28.setGeometry(QtCore.QRect(320, 140, 71, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.softwareTab)
        self.label_29.setGeometry(QtCore.QRect(319, 170, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.softwareTab)
        self.label_30.setGeometry(QtCore.QRect(319, 199, 71, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_32 = QtGui.QLabel(self.softwareTab)
        self.label_32.setGeometry(QtCore.QRect(319, 230, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.categUnlock = QtGui.QLineEdit(self.softwareTab)
        self.categUnlock.setEnabled(True)
        self.categUnlock.setGeometry(QtCore.QRect(400, 170, 81, 20))
        self.categUnlock.setObjectName(_fromUtf8("categUnlock"))
        self.label_31 = QtGui.QLabel(self.softwareTab)
        self.label_31.setGeometry(QtCore.QRect(320, 259, 71, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.addCategoryButton = QtGui.QPushButton(self.softwareTab)
        self.addCategoryButton.setEnabled(False)
        self.addCategoryButton.setGeometry(QtCore.QRect(449, 85, 103, 22))
        self.addCategoryButton.setObjectName(_fromUtf8("addCategoryButton"))
        self.label_33 = QtGui.QLabel(self.softwareTab)
        self.label_33.setGeometry(QtCore.QRect(320, 290, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.categNameGen = QtGui.QLineEdit(self.softwareTab)
        self.categNameGen.setGeometry(QtCore.QRect(440, 320, 111, 21))
        self.categNameGen.setObjectName(_fromUtf8("categNameGen"))
        self.label_34 = QtGui.QLabel(self.softwareTab)
        self.label_34.setGeometry(QtCore.QRect(319, 320, 121, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.label_24 = QtGui.QLabel(self.softwareTab)
        self.label_24.setGeometry(QtCore.QRect(20, 230, 89, 39))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.softwareTab)
        self.label_25.setGeometry(QtCore.QRect(20, 260, 89, 39))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_6 = QtGui.QLabel(self.softwareTab)
        self.label_6.setGeometry(QtCore.QRect(20, 290, 89, 39))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.categDesc = QtGui.QLineEdit(self.softwareTab)
        self.categDesc.setGeometry(QtCore.QRect(400, 140, 151, 20))
        self.categDesc.setObjectName(_fromUtf8("categDesc"))
        self.label_35 = QtGui.QLabel(self.softwareTab)
        self.label_35.setGeometry(QtCore.QRect(320, 110, 51, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(12)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.categPopularity = QtGui.QLineEdit(self.softwareTab)
        self.categPopularity.setGeometry(QtCore.QRect(400, 200, 81, 20))
        self.categPopularity.setObjectName(_fromUtf8("categPopularity"))
        self.categRetention = QtGui.QLineEdit(self.softwareTab)
        self.categRetention.setGeometry(QtCore.QRect(400, 230, 81, 20))
        self.categRetention.setObjectName(_fromUtf8("categRetention"))
        self.categTimeScale = QtGui.QLineEdit(self.softwareTab)
        self.categTimeScale.setGeometry(QtCore.QRect(400, 260, 81, 20))
        self.categTimeScale.setObjectName(_fromUtf8("categTimeScale"))
        self.categIterative = QtGui.QLineEdit(self.softwareTab)
        self.categIterative.setGeometry(QtCore.QRect(400, 290, 81, 20))
        self.categIterative.setObjectName(_fromUtf8("categIterative"))
        self.retention = QtGui.QLineEdit(self.softwareTab)
        self.retention.setGeometry(QtCore.QRect(95, 240, 121, 20))
        self.retention.setObjectName(_fromUtf8("retention"))
        self.random = QtGui.QLineEdit(self.softwareTab)
        self.random.setGeometry(QtCore.QRect(95, 210, 121, 20))
        self.random.setObjectName(_fromUtf8("random"))
        self.population = QtGui.QLineEdit(self.softwareTab)
        self.population.setGeometry(QtCore.QRect(95, 300, 121, 20))
        self.population.setObjectName(_fromUtf8("population"))
        self.iterative = QtGui.QLineEdit(self.softwareTab)
        self.iterative.setGeometry(QtCore.QRect(95, 270, 121, 20))
        self.iterative.setObjectName(_fromUtf8("iterative"))
        self.line_6 = QtGui.QFrame(self.softwareTab)
        self.line_6.setGeometry(QtCore.QRect(300, 0, 3, 440))
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.tabWidget.addTab(self.softwareTab, _fromUtf8(""))
        self.featuresTab = QtGui.QWidget()
        self.featuresTab.setObjectName(_fromUtf8("featuresTab"))
        self.deleteFeatureButton = QtGui.QPushButton(self.featuresTab)
        self.deleteFeatureButton.setEnabled(True)
        self.deleteFeatureButton.setGeometry(QtCore.QRect(389, 40, 94, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(9)
        self.deleteFeatureButton.setFont(font)
        self.deleteFeatureButton.setObjectName(_fromUtf8("deleteFeatureButton"))
        self.featureNameEdit = QtGui.QLineEdit(self.featuresTab)
        self.featureNameEdit.setEnabled(True)
        self.featureNameEdit.setGeometry(QtCore.QRect(250, 10, 121, 23))
        self.featureNameEdit.setMaximumSize(QtCore.QSize(121, 16777215))
        self.featureNameEdit.setText(_fromUtf8(""))
        self.featureNameEdit.setObjectName(_fromUtf8("featureNameEdit"))
        self.renameFeatureButton = QtGui.QPushButton(self.featuresTab)
        self.renameFeatureButton.setEnabled(True)
        self.renameFeatureButton.setGeometry(QtCore.QRect(489, 70, 121, 23))
        self.renameFeatureButton.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(9)
        self.renameFeatureButton.setFont(font)
        self.renameFeatureButton.setObjectName(_fromUtf8("renameFeatureButton"))
        self.addFeatureButton = QtGui.QPushButton(self.featuresTab)
        self.addFeatureButton.setEnabled(True)
        self.addFeatureButton.setGeometry(QtCore.QRect(389, 9, 94, 25))
        self.addFeatureButton.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(9)
        self.addFeatureButton.setFont(font)
        self.addFeatureButton.setObjectName(_fromUtf8("addFeatureButton"))
        self.fComboBox = QtGui.QComboBox(self.featuresTab)
        self.fComboBox.setEnabled(True)
        self.fComboBox.setGeometry(QtCore.QRect(250, 40, 121, 23))
        self.fComboBox.setEditable(False)
        self.fComboBox.setObjectName(_fromUtf8("fComboBox"))
        self.newNameEdit = QtGui.QLineEdit(self.featuresTab)
        self.newNameEdit.setGeometry(QtCore.QRect(389, 70, 94, 25))
        self.newNameEdit.setObjectName(_fromUtf8("newNameEdit"))
        self.dependencyComboBox = QtGui.QComboBox(self.featuresTab)
        self.dependencyComboBox.setEnabled(False)
        self.dependencyComboBox.setGeometry(QtCore.QRect(810, 130, 121, 31))
        self.dependencyComboBox.setObjectName(_fromUtf8("dependencyComboBox"))
        self.deleteDependencyBttn = QtGui.QPushButton(self.featuresTab)
        self.deleteDependencyBttn.setEnabled(False)
        self.deleteDependencyBttn.setGeometry(QtCore.QRect(940, 130, 111, 31))
        self.deleteDependencyBttn.setObjectName(_fromUtf8("deleteDependencyBttn"))
        self.label_13 = QtGui.QLabel(self.featuresTab)
        self.label_13.setGeometry(QtCore.QRect(9, 80, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.featuresTab)
        self.label_14.setGeometry(QtCore.QRect(9, 110, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_10 = QtGui.QLabel(self.featuresTab)
        self.label_10.setGeometry(QtCore.QRect(9, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.featureUnlock = QtGui.QLineEdit(self.featuresTab)
        self.featureUnlock.setEnabled(True)
        self.featureUnlock.setGeometry(QtCore.QRect(90, 50, 113, 21))
        self.featureUnlock.setObjectName(_fromUtf8("featureUnlock"))
        self.label_12 = QtGui.QLabel(self.featuresTab)
        self.label_12.setGeometry(QtCore.QRect(9, 50, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.ServerLabel = QtGui.QLabel(self.featuresTab)
        self.ServerLabel.setGeometry(QtCore.QRect(9, 230, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(11)
        self.ServerLabel.setFont(font)
        self.ServerLabel.setObjectName(_fromUtf8("ServerLabel"))
        self.label_11 = QtGui.QLabel(self.featuresTab)
        self.label_11.setGeometry(QtCore.QRect(9, 140, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_17 = QtGui.QLabel(self.featuresTab)
        self.label_17.setGeometry(QtCore.QRect(9, 200, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_15 = QtGui.QLabel(self.featuresTab)
        self.label_15.setGeometry(QtCore.QRect(9, 170, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.savechanges = QtGui.QPushButton(self.featuresTab)
        self.savechanges.setEnabled(True)
        self.savechanges.setGeometry(QtCore.QRect(500, 10, 121, 23))
        self.savechanges.setObjectName(_fromUtf8("savechanges"))
        self.fromEdit = QtGui.QLineEdit(self.featuresTab)
        self.fromEdit.setGeometry(QtCore.QRect(10, 350, 121, 21))
        self.fromEdit.setObjectName(_fromUtf8("fromEdit"))
        self.vitalCheckbox = QtGui.QRadioButton(self.featuresTab)
        self.vitalCheckbox.setGeometry(QtCore.QRect(140, 310, 61, 43))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(10)
        self.vitalCheckbox.setFont(font)
        self.vitalCheckbox.setObjectName(_fromUtf8("vitalCheckbox"))
        self.fromCheckbox = QtGui.QRadioButton(self.featuresTab)
        self.fromCheckbox.setGeometry(QtCore.QRect(140, 350, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(10)
        self.fromCheckbox.setFont(font)
        self.fromCheckbox.setObjectName(_fromUtf8("fromCheckbox"))
        self.forcedCheckbox = QtGui.QRadioButton(self.featuresTab)
        self.forcedCheckbox.setEnabled(True)
        self.forcedCheckbox.setGeometry(QtCore.QRect(10, 310, 121, 43))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(10)
        self.forcedCheckbox.setFont(font)
        self.forcedCheckbox.setObjectName(_fromUtf8("forcedCheckbox"))
        self.line = QtGui.QFrame(self.featuresTab)
        self.line.setGeometry(QtCore.QRect(220, 0, 31, 391))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.featuresTab)
        self.line_2.setGeometry(QtCore.QRect(0, 310, 234, 3))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.featuresTab)
        self.line_3.setGeometry(QtCore.QRect(0, 390, 234, 3))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.addDependencyButton = QtGui.QPushButton(self.featuresTab)
        self.addDependencyButton.setEnabled(True)
        self.addDependencyButton.setGeometry(QtCore.QRect(620, 320, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(9)
        self.addDependencyButton.setFont(font)
        self.addDependencyButton.setObjectName(_fromUtf8("addDependencyButton"))
        self.label_9 = QtGui.QLabel(self.featuresTab)
        self.label_9.setGeometry(QtCore.QRect(245, 325, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_16 = QtGui.QLabel(self.featuresTab)
        self.label_16.setGeometry(QtCore.QRect(430, 325, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Raavi"))
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.dependency_software = QtGui.QLineEdit(self.featuresTab)
        self.dependency_software.setGeometry(QtCore.QRect(310, 320, 101, 21))
        self.dependency_software.setObjectName(_fromUtf8("dependency_software"))
        self.dependency_feature = QtGui.QLineEdit(self.featuresTab)
        self.dependency_feature.setGeometry(QtCore.QRect(490, 320, 113, 21))
        self.dependency_feature.setObjectName(_fromUtf8("dependency_feature"))
        self.line_4 = QtGui.QFrame(self.featuresTab)
        self.line_4.setGeometry(QtCore.QRect(230, 310, 510, 3))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(self.featuresTab)
        self.line_5.setGeometry(QtCore.QRect(230, 390, 510, 3))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.dComboBox = QtGui.QComboBox(self.featuresTab)
        self.dComboBox.setEnabled(True)
        self.dComboBox.setGeometry(QtCore.QRect(250, 350, 161, 23))
        self.dComboBox.setEditable(False)
        self.dComboBox.setObjectName(_fromUtf8("dComboBox"))
        self.featureUsability = QtGui.QLineEdit(self.featuresTab)
        self.featureUsability.setGeometry(QtCore.QRect(90, 140, 113, 20))
        self.featureUsability.setObjectName(_fromUtf8("featureUsability"))
        self.featureInnovation = QtGui.QLineEdit(self.featuresTab)
        self.featureInnovation.setGeometry(QtCore.QRect(90, 110, 113, 20))
        self.featureInnovation.setObjectName(_fromUtf8("featureInnovation"))
        self.featureDevTime = QtGui.QLineEdit(self.featuresTab)
        self.featureDevTime.setGeometry(QtCore.QRect(90, 80, 113, 20))
        self.featureDevTime.setObjectName(_fromUtf8("featureDevTime"))
        self.featureStability = QtGui.QLineEdit(self.featuresTab)
        self.featureStability.setGeometry(QtCore.QRect(90, 170, 113, 20))
        self.featureStability.setObjectName(_fromUtf8("featureStability"))
        self.featureCodeArt = QtGui.QLineEdit(self.featuresTab)
        self.featureCodeArt.setGeometry(QtCore.QRect(90, 200, 113, 20))
        self.featureCodeArt.setObjectName(_fromUtf8("featureCodeArt"))
        self.featureServer = QtGui.QLineEdit(self.featuresTab)
        self.featureServer.setGeometry(QtCore.QRect(90, 230, 113, 20))
        self.featureServer.setObjectName(_fromUtf8("featureServer"))
        self.fDesc = QtGui.QLineEdit(self.featuresTab)
        self.fDesc.setGeometry(QtCore.QRect(90, 20, 113, 20))
        self.fDesc.setObjectName(_fromUtf8("fDesc"))
        self.tabWidget.addTab(self.featuresTab, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Modding Tool", None))
        self.openButton.setText(_translate("MainWindow", "Open File", None))
        self.saveButton.setText(_translate("MainWindow", "Save", None))
        self.newModButton.setText(_translate("MainWindow", "New Mod", None))
        self.numberOfFeaturesLayout.setText(_translate("MainWindow", "Number Of Features", None))
        self.saveSoftwareButton.setText(_translate("MainWindow", "Save Changes to Software Type", None))
        self.saveCategoryChanges.setText(_translate("MainWindow", "Save Category Changes", None))
        self.removeCategoryButton.setText(_translate("MainWindow", "Remove Category", None))
        self.label_2.setText(_translate("MainWindow", "Name       ", None))
        self.label.setText(_translate("MainWindow", "Description", None))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Category</span></p></body></html>", None))
        self.label_4.setText(_translate("MainWindow", "Random    ", None))
        self.label_3.setText(_translate("MainWindow", "InHouse", None))
        self.label_5.setText(_translate("MainWindow", "OSSpecific", None))
        self.label_7.setText(_translate("MainWindow", "Unlock     ", None))
        self.label_23.setText(_translate("MainWindow", "Name Generator", None))
        self.categoryCheckbox.setText(_translate("MainWindow", "Categories", None))
        self.label_28.setText(_translate("MainWindow", "Description", None))
        self.label_29.setText(_translate("MainWindow", "Unlock", None))
        self.label_30.setText(_translate("MainWindow", "Popularity", None))
        self.label_32.setText(_translate("MainWindow", "Retention", None))
        self.label_31.setText(_translate("MainWindow", "TimeScale", None))
        self.addCategoryButton.setText(_translate("MainWindow", "Add Category", None))
        self.label_33.setText(_translate("MainWindow", "Iterative", None))
        self.label_34.setText(_translate("MainWindow", "Name Generator", None))
        self.label_24.setText(_translate("MainWindow", "Retention", None))
        self.label_25.setText(_translate("MainWindow", "Iterative", None))
        self.label_6.setText(_translate("MainWindow", "Population ", None))
        self.label_35.setText(_translate("MainWindow", "Name", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.softwareTab), _translate("MainWindow", "Software and Categories", None))
        self.deleteFeatureButton.setText(_translate("MainWindow", "Delete Feature", None))
        self.featureNameEdit.setPlaceholderText(_translate("MainWindow", "Function", None))
        self.renameFeatureButton.setText(_translate("MainWindow", "Rename Feature", None))
        self.addFeatureButton.setText(_translate("MainWindow", "Add Feature", None))
        self.deleteDependencyBttn.setText(_translate("MainWindow", "Delete Dependency", None))
        self.label_13.setText(_translate("MainWindow", "DevTime", None))
        self.label_14.setText(_translate("MainWindow", "Innovation", None))
        self.label_10.setText(_translate("MainWindow", "Description", None))
        self.label_12.setText(_translate("MainWindow", "Unlock", None))
        self.ServerLabel.setText(_translate("MainWindow", "Server", None))
        self.label_11.setText(_translate("MainWindow", "Usability", None))
        self.label_17.setText(_translate("MainWindow", "CodeArt", None))
        self.label_15.setText(_translate("MainWindow", "Stability", None))
        self.savechanges.setText(_translate("MainWindow", "Save Changes", None))
        self.vitalCheckbox.setText(_translate("MainWindow", "Vital", None))
        self.fromCheckbox.setText(_translate("MainWindow", "From Tag", None))
        self.forcedCheckbox.setText(_translate("MainWindow", "Forced Feature", None))
        self.addDependencyButton.setText(_translate("MainWindow", "Add Dependency", None))
        self.label_9.setText(_translate("MainWindow", "Software", None))
        self.label_16.setText(_translate("MainWindow", "Feature", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.featuresTab), _translate("MainWindow", "Features", None))

